name: make nightly

permissions:
  contents: write

on:
  schedule:
    - cron: '45 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build arm64-v8a APK
        run: gradle assembleDebug -PabiFilters=arm64-v8a

      - name: Install apksigner
        run: |
          sudo apt-get update
          sudo apt-get install -y apksigner

      - name: Create dummy keystore
        run: |
          keytool -genkeypair -v \
            -keystore dummy.keystore \
            -storepass test1234 \
            -alias dummykey \
            -keypass test1234 \
            -dname "CN=Test, OU=Test, O=Test, L=Test, S=Test, C=PH" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000

      - name: Sign APK with apksigner
        run: |
          apksigner sign \
            --ks dummy.keystore \
            --ks-key-alias dummykey \
            --ks-pass pass:test1234 \
            --key-pass pass:test1234 \
            --out DotSkii-arm64-v8a.apk \
            app/build/outputs/apk/debug/app-arm64-v8a-debug.apk

      - name: Verify APK signature
        run: apksigner verify DotSkii-arm64-v8a.apk

      - name: Get current date time in PH time
        id: datetime
        run: |
          PH_TIME=$(TZ='Asia/Manila' date +'%Y%m%d_%I%M%p')
          echo "filename_time=$PH_TIME" >> $GITHUB_OUTPUT

      - name: Create zip file with APK
        run: |
          mv DotSkii-arm64-v8a.apk "DotSkii_${{ steps.datetime.outputs.filename_time }}.apk"
          zip "DotSkii_build_${{ steps.datetime.outputs.filename_time }}.zip" \
            "DotSkii_${{ steps.datetime.outputs.filename_time }}.apk"

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./DotSkii_build_${{ steps.datetime.outputs.filename_time }}.zip
          name: DotSkii-build-${{ steps.datetime.outputs.filename_time }}
