name: make nightly (Dotskii)

permissions:
  contents: write

on:
  schedule:
    - cron: '45 18 * * *'  # runs daily at 2:45 AM PH time (UTC+8)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Install apksigner
        run: |
          sudo apt-get update
          sudo apt-get install -y apksigner

      - name: Create dummy keystore
        run: |
          keytool -genkeypair -v \
            -keystore dummy.keystore \
            -storepass test1234 \
            -alias dummykey \
            -keypass test1234 \
            -dname "CN=Dotskii, OU=Dotskii, O=Dotskii, L=SG, S=SG, C=PH" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000

      - name: Sign APK
        run: |
          apksigner sign \
            --ks dummy.keystore \
            --ks-key-alias dummykey \
            --ks-pass pass:test1234 \
            --key-pass pass:test1234 \
            --out Dotskii-signed.apk \
            app/build/outputs/apk/debug/app-debug.apk

      - name: Verify APK signature
        run: apksigner verify Dotskii-signed.apk

      - name: Get current date time (PH timezone)
        id: datetime
        run: |
          PH_TIME=$(TZ='Asia/Manila' date +'%Y%m%d_%I%M%p')
          echo "filename_time=$PH_TIME" >> $GITHUB_OUTPUT

      - name: Create zip with APK
        run: |
          mv Dotskii-signed.apk "Dotskii_${{ steps.datetime.outputs.filename_time }}.apk"
          zip "Dotskii_build_${{ steps.datetime.outputs.filename_time }}.zip" \
            "Dotskii_${{ steps.datetime.outputs.filename_time }}.apk"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dotskii-build-${{ steps.datetime.outputs.filename_time }}
          path: ./Dotskii_build_${{ steps.datetime.outputs.filename_time }}.zip
